### ISSUE TITLE
Nefunguje ve Windows

### ISSUE THREAD

**Issue by berk76** [underground-lab/zelezobeton#1]
Ahoj Michale, 

zkouším pod Windows spustit `poerty install` ale má problémy s vytvořením virtuálního prostředí. Důvodem je čárka v `name = "Železo, beton"` v souboru `pyproject.toml`. On to jméno použije v názvu toho virtuálního prostředí a přinejmenším ve Windows je to problém. Když jí odstraním tak to funguje v pořádku.

Dál vidím že schází `.gitignore` a v něm `__pycache__`.

Jarda

**Comment by mportesdev** [comment]
`.gitignore` jsem přidal.

**Comment by berk76** [comment]
Já ti nevím jestli je `poetry config virtualenvs.in-project true` to správné řešení. Mám pocit že poetry to `name` používá jako jméno modulu. Zkusil si třeba `poetry build`?

**Comment by mportesdev** [comment]
Už mě to taky napadlo a v `pyproject.toml` jsem to změnil.

**Comment by berk76** [comment]
Ještě bys měl přejmenovat adresář `game` na `zelezobeton`. Pak bude fungovat správně i build.

**Comment by mportesdev** [comment]
> Ještě bys měl přejmenovat adresář `game` na `zelezobeton`. Pak bude fungovat správně i build.

Publikovat balíček na PyPI neplánuju, aspoň ne v nejbližší době. Chci se nejdřív trochu zamyslet nad strukturou toho projektu. Chtěl bych, aby byly od sebe co nejvíc oddělené webové GUI, engine hry a data hry.
